Update

diff --git a/uit-serverd_1.0-1_amd64/DEBIAN/postinst b/uit-serverd_1.0-1_amd64/DEBIAN/postinst
--- a/uit-serverd_1.0-1_amd64/DEBIAN/postinst
+++ b/uit-serverd_1.0-1_amd64/DEBIAN/postinst
@@ -1,125 +1,106 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-set -e
+set -eu +o pipefail
 
 if [[ $EUID -ne 0 ]]; then
 	 echo "This script must be run as root" 
 	 exit 1
 fi
 
-if [[ ! -f /etc/uit-toolbox/uit-toolbox.json ]]; then
-	echo "Missing /etc/uit-toolbox/uit-toolbox.json. Exiting..."
-	exit 1
-fi
-
-if [[ -n $(dpkg -s uit-api 2>/dev/null) ]]; then
-	# Directory contains old inventory images, can't purge until they're migrated
-	dpkg --remove uit-api || true
-fi
-if [[ -n $(dpkg -s uit-client 2>/dev/null) ]]; then
-	# No important data, can purge
-	dpkg --purge uit-client || true
-fi
-if [[ -n $(dpkg -s uit-web 2>/dev/null) ]]; then
-	# Might contain important date, can't purge until I check
-	dpkg --remove uit-web || true
-fi
-
-## Users and groups
-if [[ $(groups cameron | grep 'uit'; echo $?) == "1" ]]; then
-  groupadd uit
-  usermod --append --groups uit cameron
-fi
-if [[ $(id -u uitweb &>/dev/null; echo $?) == "1" ]]; then
-    sudo useradd --system --no-create-home --shell /usr/sbin/nologin uitweb
-fi
-
-## Directory creation
-# Directories for uit-client (HTTP boot, uit-client package, configs)
-mkdir -p /srv/uit-toolbox/client/configs/
-mkdir -p /srv/uit-toolbox/client/iso/
-mkdir -p /srv/uit-toolbox/client/pkg/
-mkdir -p /srv/uit-toolbox/client/src/
-
-# Directories for uit-api config
-mkdir -p /etc/uit-toolbox/certs.d/
-mkdir -p /etc/uit-toolbox/postgresql.d/
-
-# Directories for NFS
-mkdir -p /srv/nfs/uit-toolbox/images
-
-## Server config
 unset 'configArr'
 declare -A configArr
 
+function createNecessaryDirs() {
+	# Directories for uit-client (HTTP boot, uit-client package, configs)
+	mkdir -p /srv/uit-toolbox/client/configs/
+	mkdir -p /srv/uit-toolbox/client/iso/
+	mkdir -p /srv/uit-toolbox/client/pkg/
+	mkdir -p /srv/uit-toolbox/client/src/
+
+	# Directories for uit-api config
+	mkdir -p /etc/uit-toolbox/certs.d/
+	mkdir -p /etc/uit-toolbox/postgresql.d/
+
+	# Directories for NFS
+	mkdir -p /srv/nfs/uit-toolbox/images
+}
+
 # Get config values from /etc/uit-toolbox/uit-toolbox.json
 getConfigValue() {
-    local key="$1"
-    local trim_spaces="${2:-true}"
-    local value
-    value=$(jq -r ".${key}" /etc/uit-toolbox/uit-toolbox.json)
-    if [[ "$trim_spaces" == "true" ]]; then
-        value=$(echo "$value" | tr -d '[:space:]')
-    fi
-		if [[ $key == "UIT_SERVER_WAN_ALLOWED_IP" || $key == "UIT_SERVER_LAN_ALLOWED_IP" ]]; then
-			value=$(printf "%s" "$value" | tr -d '\n []"')
-    fi
-    echo "$value"
+	local key="$1"
+	local trim_spaces="${2:-true}"
+	local value
+	value=$(jq -r ".${key}" /etc/uit-toolbox/uit-toolbox.json)
+	if [[ ! -f /etc/uit-toolbox/uit-toolbox.json || -z $value ]];
+	if [[ "$trim_spaces" == "true" ]]; then
+			value=$(echo "$value" | tr -d '[:space:]')
+	fi
+	if [[ $key == "UIT_SERVER_WAN_ALLOWED_IP" || $key == "UIT_SERVER_LAN_ALLOWED_IP" ]]; then
+		value=$(printf "%s" "$value" | tr -d '\n []"')
+	fi
+	echo "$value"
 }
-
-# Load config values (values that need spaces preserved are marked with 'false')
-configArr[UIT_SERVER_ADMIN_PASSWD]=$(getConfigValue "UIT_SERVER_ADMIN_PASSWD")
-configArr[UIT_CLIENT_DB_PASSWD]=$(getConfigValue "UIT_CLIENT_DB_PASSWD")
-configArr[UIT_WEBMASTER_NAME]=$(getConfigValue "UIT_WEBMASTER_NAME" false)
-configArr[UIT_WEBMASTER_EMAIL]=$(getConfigValue "UIT_WEBMASTER_EMAIL")
-configArr[UIT_SERVER_WAN_IF]=$(getConfigValue "UIT_SERVER_WAN_IF")
-configArr[UIT_SERVER_WAN_IP_ADDRESS]=$(getConfigValue "UIT_SERVER_WAN_IP_ADDRESS")
-configArr[UIT_SERVER_LAN_IF]=$(getConfigValue "UIT_SERVER_LAN_IF")
-configArr[UIT_SERVER_LAN_IP_ADDRESS]=$(getConfigValue "UIT_SERVER_LAN_IP_ADDRESS")
-configArr[UIT_SERVER_WAN_ALLOWED_IP]=$(getConfigValue "UIT_SERVER_WAN_ALLOWED_IP" false)
-configArr[UIT_SERVER_LAN_ALLOWED_IP]=$(getConfigValue "UIT_SERVER_LAN_ALLOWED_IP" false)
-configArr[UIT_WEB_DB_PASSWD]=$(openssl rand 30 | hexdump | tr -d '\n' | sed 's/[[:space:]]//g' | head -n1 | md5sum | awk '{print $1}')
-jq '.UIT_WEB_DB_PASSWD = "'"${configArr[UIT_WEB_DB_PASSWD]}"'"' /etc/uit-toolbox/uit-toolbox.json > /etc/uit-toolbox/uit-toolbox.tmp && mv /etc/uit-toolbox/uit-toolbox.tmp /etc/uit-toolbox/uit-toolbox.json
-configArr[UIT_WEB_DB_HOST]=$(getConfigValue "UIT_WEB_DB_HOST")
-configArr[UIT_WEB_DB_PORT]=$(getConfigValue "UIT_WEB_DB_PORT")
-configArr[UIT_WEB_DB_USERNAME]=$(getConfigValue "UIT_WEB_DB_USERNAME")
-configArr[UIT_WEB_HTTPS_PORT]=$(getConfigValue "UIT_WEB_HTTPS_PORT")
-configArr[UIT_WEB_TLS_CERT_FILE]=$(getConfigValue "UIT_WEB_TLS_CERT_FILE")
-configArr[UIT_WEB_TLS_KEY_FILE]=$(getConfigValue "UIT_WEB_TLS_KEY_FILE")
-configArr[UIT_WEB_RATE_LIMIT_BURST]=$(getConfigValue "UIT_WEB_RATE_LIMIT_BURST")
-configArr[UIT_WEB_RATE_LIMIT_INTERVAL]=$(getConfigValue "UIT_WEB_RATE_LIMIT_INTERVAL")
-configArr[UIT_WEB_RATE_LIMIT_BAN_DURATION]=$(getConfigValue "UIT_WEB_RATE_LIMIT_BAN_DURATION")
-configArr[UIT_SERVER_LOG_LEVEL]=$(getConfigValue "UIT_SERVER_LOG_LEVEL")
 
 function checkNullConfigVals() {
-for checkVal in ${!configArr[@]}; do
-  if [[ -z ${configArr[$checkVal]} ]]; then
-    echo "[Error] Missing/NULL parameter ${checkVal} in /etc/uit-toolbox/uit-toolbox.json"
-    echo ""
-    read -p "Value for ${checkVal} is missing. Continue? [y/N] " userInput
-    if [[ -z $userInput || $userInput == "n" || $userInput == "N" ]]; then
-      echo "Exiting..."
-      exit 1
-      elif [[ $userInput == "y" || $userInput == "Y" ]]; then
-        :
-      else checkNullConfigVals
-    fi
-  fi
-done
+	local configKeys=("$@")
+	for checkVal in "${configKeys[@]}"; do
+		if [[ -z ${configArr[$checkVal]} ]]; then
+			echo "[Error] Missing/NULL parameter ${checkVal} in /etc/uit-toolbox/uit-toolbox.json"
+			echo ""
+			read -p "Value for ${checkVal} is missing. Continue? [y/N] " userInput
+			if [[ -z $userInput || $userInput == "n" || $userInput == "N" ]]; then
+				echo "Exiting..."
+				exit 1
+				elif [[ $userInput == "y" || $userInput == "Y" ]]; then
+					:
+				else checkNullConfigVals "${configKeys[@]}"
+			fi
+		fi
+	done
 }
-checkNullConfigVals
 
-for i in ${!configArr[@]}; do
-  for file in $(find /usr/sbin/ -type f -name 'uit-*'; find /etc/dnsmasq.d/uit-dhcp.conf -type f; find /etc/uit-toolbox/certs.d/ -type f -name '*.cfg'; find /etc/chrony/conf.d/ -type f -name *.conf; find /etc/dnsmasq.d/ -type f -name *.conf); do
-    if [[ -f $file ]]; then
-      sanitizedValue=${configArr[$i]//\//\\/}
-      sed --in-place "s/${i}/${sanitizedValue}/g" ${file}
-      else
-      echo "File ${file} does not exist. Exiting..."
-      exit 1
-    fi
-  done
-done
+function initConfig() {
+	## Server config
+
+	# Load config values (values that need spaces preserved are marked with 'false')
+	configArr[UIT_SERVER_ADMIN_PASSWD]=$(getConfigValue "UIT_SERVER_ADMIN_PASSWD")
+	configArr[UIT_CLIENT_DB_PASSWD]=$(getConfigValue "UIT_CLIENT_DB_PASSWD")
+	configArr[UIT_WEBMASTER_NAME]=$(getConfigValue "UIT_WEBMASTER_NAME" false)
+	configArr[UIT_WEBMASTER_EMAIL]=$(getConfigValue "UIT_WEBMASTER_EMAIL")
+	configArr[UIT_SERVER_WAN_IF]=$(getConfigValue "UIT_SERVER_WAN_IF")
+	configArr[UIT_SERVER_WAN_IP_ADDRESS]=$(getConfigValue "UIT_SERVER_WAN_IP_ADDRESS")
+	configArr[UIT_SERVER_LAN_IF]=$(getConfigValue "UIT_SERVER_LAN_IF")
+	configArr[UIT_SERVER_LAN_IP_ADDRESS]=$(getConfigValue "UIT_SERVER_LAN_IP_ADDRESS")
+	configArr[UIT_SERVER_WAN_ALLOWED_IP]=$(getConfigValue "UIT_SERVER_WAN_ALLOWED_IP" false)
+	configArr[UIT_SERVER_LAN_ALLOWED_IP]=$(getConfigValue "UIT_SERVER_LAN_ALLOWED_IP" false)
+	configArr[UIT_WEB_DB_PASSWD]=$(openssl rand 30 | hexdump | tr -d '\n' | sed 's/[[:space:]]//g' | head -n1 | md5sum | awk '{print $1}')
+	jq '.UIT_WEB_DB_PASSWD = "'"${configArr[UIT_WEB_DB_PASSWD]}"'"' /etc/uit-toolbox/uit-toolbox.json > /etc/uit-toolbox/uit-toolbox.tmp && mv /etc/uit-toolbox/uit-toolbox.tmp /etc/uit-toolbox/uit-toolbox.json
+	configArr[UIT_WEB_DB_HOST]=$(getConfigValue "UIT_WEB_DB_HOST")
+	configArr[UIT_WEB_DB_PORT]=$(getConfigValue "UIT_WEB_DB_PORT")
+	configArr[UIT_WEB_DB_USERNAME]=$(getConfigValue "UIT_WEB_DB_USERNAME")
+	configArr[UIT_WEB_HTTPS_PORT]=$(getConfigValue "UIT_WEB_HTTPS_PORT")
+	configArr[UIT_WEB_TLS_CERT_FILE]=$(getConfigValue "UIT_WEB_TLS_CERT_FILE")
+	configArr[UIT_WEB_TLS_KEY_FILE]=$(getConfigValue "UIT_WEB_TLS_KEY_FILE")
+	configArr[UIT_WEB_RATE_LIMIT_BURST]=$(getConfigValue "UIT_WEB_RATE_LIMIT_BURST")
+	configArr[UIT_WEB_RATE_LIMIT_INTERVAL]=$(getConfigValue "UIT_WEB_RATE_LIMIT_INTERVAL")
+	configArr[UIT_WEB_RATE_LIMIT_BAN_DURATION]=$(getConfigValue "UIT_WEB_RATE_LIMIT_BAN_DURATION")
+	configArr[UIT_SERVER_LOG_LEVEL]=$(getConfigValue "UIT_SERVER_LOG_LEVEL")
+
+	for i in ${!configArr[@]}; do
+		for file in $(find /usr/sbin/ -type f -name 'uit-*'; find /etc/dnsmasq.d/uit-dhcp.conf -type f; find /etc/uit-toolbox/certs.d/ -type f -name '*.cfg'; find /etc/chrony/conf.d/ -type f -name *.conf; find /etc/dnsmasq.d/ -type f -name *.conf); do
+			if [[ -f $file ]]; then
+				sanitizedValue=${configArr[$i]//\//\\/}
+				sed --in-place "s/${i}/${sanitizedValue}/g" ${file}
+				else
+				echo "File ${file} does not exist. Exiting..."
+				exit 1
+			fi
+		done
+	done
+
+	checkNullConfigVals "${!configArr[@]}"
+	echo ${configArr[@]}
+}
 
 
 ## Web server setup
@@ -184,3 +165,37 @@ find /opt/uit-toolbox/sql-backups -type f -exec chmod 660 {} \;
 ## Misc setup
 mkdir -p /opt/uit-toolbox/sql-backups
 echo -e "\n" >> /etc/cron.d/uit-cron
+
+function main() {
+
+	if [[ ! -f /etc/uit-toolbox/uit-toolbox.json ]]; then
+		echo "Missing /etc/uit-toolbox/uit-toolbox.json. Exiting..."
+		exit 1
+	fi
+
+	if [[ -n $(dpkg -s uit-api 2>/dev/null) ]]; then
+		# Directory contains old inventory images, can't purge until they're migrated
+		dpkg --remove uit-api || true
+	fi
+	if [[ -n $(dpkg -s uit-client 2>/dev/null) ]]; then
+		# No important data, can purge
+		dpkg --purge uit-client || true
+	fi
+	if [[ -n $(dpkg -s uit-web 2>/dev/null) ]]; then
+		# Might contain important date, can't purge until I check
+		dpkg --remove uit-web || true
+	fi
+
+	## Users and groups
+	if [[ $(groups cameron | grep 'uit'; echo $?) == "1" ]]; then
+		groupadd uit
+		usermod --append --groups uit cameron
+	fi
+	if [[ $(id -u uitweb &>/dev/null; echo $?) == "1" ]]; then
+			sudo useradd --system --no-create-home --shell /usr/sbin/nologin uitweb
+	fi
+
+	createNecessaryDirs
+	initConfig
+}
+main
